const products = [
  {
    id: 1,
    name: "BulletPof",
    description: "fhfkjdvndjvbhoes",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    category: 1,
  },
  {
    id: 2,
    name: "Shoes",
    description:
      "these are the shoesthese are the shoesthese are the shoesthese are the shoesthese are the shoesthese are the shoesthese are the shoesthese are the shoesthese are the shoes",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    category: 1,
  },
  {
    id: 3,
    name: "Shoes",
    description: "these are the shoes",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    category: 1,
  },
  {
    id: 4,
    name: "Pants",
    description: "these are the shoes",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    category: 1,
  },
  {
    id: 5,
    name: "hat",
    description: "these are the shoes",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    category: 1,
  },
  {
    id: 6,
    name: "other",
    description: "these are the shoes",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    category: 1,
  },
  {
    id: 7,
    name: "Shoes",
    description: "these are the shoes",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    category: 1,
  },
  {
    id: 8,
    name: "Pants",
    description: "these are the shoes",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    category: 1,
  },
  {
    id: 9,
    name: "hat",
    description:
      "This is a hat that is really ncie and comdy, wherr it wehenevr you wanfgfvnefkjvnfekjvnfkjvnfkjv jvkjdfvn nkjkj  kjh kfh kerjhkjfh kjejh gkjef  g hkerjg ek gkjleghaekrj gh",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    category: 1,
  },
  {
    id: 10,
    name: "other",
    description: "these are the shoes",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    category: 1,
  },
  {
    id: 11,
    name: "Pants",
    description: "these are the shoes",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    category: 1,
  },
];

module.exports = products;
