const products = [
  {
    id: 1,
    name: "Bulletproof",
    description: "This is the bullet proof vest",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    categoryId: 1,
  },
  {
    id: 2,
    name: "Shoes",
    description: "These are the shoes of your dreams",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 9,
    categoryId: 1,
  },
  {
    id: 3,
    name: "Shoes",
    description: "these are the shoes",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 20,
    categoryId: 1,
  },
  {
    id: 4,
    name: "Pants",
    description: "these are the shoes",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 40,
    categoryId: 1,
  },
  {
    id: 5,
    name: "Hat",
    description: "This hat is amazing, great for summer and being in the sun",
    price: 5,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    categoryId: 1,
  },
  {
    id: 6,
    name: "other",
    description: "these are the shoes",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    categoryId: 1,
  },
  {
    id: 7,
    name: "People",
    description: "Yes, you can buy people",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10.99,
    categoryId: 4,
  },
  {
    id: 8,
    name: "Pants",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta, cumque delectus. Veritatis, iusto vel eius quos libero maxime dignissimos, repellendus, ratione quaerat obcaecati beatae sequi voluptate accusantium asperiores? Eum, tempore.",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    categoryId: 1,
  },
  {
    id: 9,
    name: "hat",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dicta, cumque delectus. Veritatis, iusto vel eius quos libero maxime dignissimos, repellendus, ratione quaerat obcaecati beatae sequi voluptate accusantium asperiores? Eum, tempore.",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    categoryId: 1,
  },
  {
    id: 10,
    name: "Other Stuff",
    description:
      "These are other stuff. Great for the beach and being with your loved ones",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    categoryId: 1,
  },
  {
    id: 11,
    name: "Pants",
    description: "Some more pants",
    price: 10,
    url: "https://assets.superbalistcdn.co.za/142x206/filters:quality(75):format(jpg)/605920/original.jpg",
    stockQty: 10,
    categoryId: 1,
  },
];

module.exports = products;
